-- OZ Intelligent Proposal — base de conhecimento (patologias, ensaios, soluções, etc.)
-- Correr depois de 001_schema.sql. Idempotente: pode ser executado novamente para atualizar os dados.
-- Os códigos são uma proposta interna; not_in_manual = true marca o que não consta do manual base.
-- Conteúdo técnico (causas, ensaios, severidade, soluções) a validar por um engenheiro da OZ.

create table if not exists kb_construction_types (code text primary key, category text not null, name text not null, notes text, not_in_manual boolean not null default false);
create table if not exists kb_elements (code text primary key, name text not null, not_in_manual boolean not null default false);
create table if not exists kb_causes (code text primary key, name text not null, not_in_manual boolean not null default false);
create table if not exists kb_tests (code text primary key, name text not null, test_group text, service_id text references services(service_id), not_in_manual boolean not null default false);
create table if not exists kb_solutions (code text primary key, name text not null, not_in_manual boolean not null default false);
create table if not exists kb_severity (level int primary key check (level between 1 and 4), name text not null, meaning text, action text);
create table if not exists kb_pathology_groups (code text primary key, name text not null);
create table if not exists kb_pathologies (
  code text primary key, group_code text not null references kb_pathology_groups(code), name text not null,
  sev_min int not null references kb_severity(level), sev_max int not null references kb_severity(level),
  not_in_manual boolean not null default false, active boolean not null default true);
create table if not exists kb_pathology_causes (pathology_code text references kb_pathologies(code) on delete cascade, cause_code text references kb_causes(code), primary key (pathology_code, cause_code));
create table if not exists kb_pathology_tests (pathology_code text references kb_pathologies(code) on delete cascade, test_code text references kb_tests(code), primary key (pathology_code, test_code));
create table if not exists kb_pathology_solutions (pathology_code text references kb_pathologies(code) on delete cascade, solution_code text references kb_solutions(code), primary key (pathology_code, solution_code));
create index if not exists kb_pc_cause on kb_pathology_causes(cause_code);
create index if not exists kb_pt_test on kb_pathology_tests(test_code);
create index if not exists kb_ps_sol on kb_pathology_solutions(solution_code);
create table if not exists kb_services (code text primary key, name text not null, unit text, not_in_manual boolean not null default false);
create table if not exists kb_client_info_items (code text primary key, name text not null, not_in_manual boolean not null default false);
create table if not exists kb_report_sections (code text primary key, name text not null, content text, not_in_manual boolean not null default false);
create table if not exists kb_equipment (code text primary key, name text not null, items text, not_in_manual boolean not null default false);
create table if not exists kb_materials (code text primary key, name text not null, items text);
create table if not exists kb_reference_notes (code text primary key, title text not null, content text, not_in_manual boolean not null default false);

insert into kb_construction_types (code,category,name,notes,not_in_manual) values
('TIP-ED-01','Sistema construtivo','Edifício antigo de alvenaria de pedra','Humidade, paredes de várias folhas, pavimentos de madeira, sismo',false),
('TIP-ED-02','Sistema construtivo','Edifício pombalino (gaiola, pós-1755)','Madeira degradada, alterações à gaiola, ligações, sismo',false),
('TIP-ED-03','Sistema construtivo','Edifício "gaioleiro" (finais séc. XIX e início XX)','Paredes esbeltas, madeira, desligamento paredes–pavimentos',false),
('TIP-ED-04','Sistema construtivo','Betão armado "de placa" (c. 1930–1960)','Betão pobre, recobrimentos baixos, carbonatação',false),
('TIP-ED-05','Sistema construtivo','Betão armado 1960–1980','Carbonatação, varandas e consolas, cloretos em zona costeira',false),
('TIP-ED-06','Sistema construtivo','Betão armado pós-RSA/REBAP (1983+)','Falhas de execução, infiltrações, juntas',false),
('TIP-ED-07','Sistema construtivo','Betão armado recente (Eurocódigos, c. 2010+)','Falhas de execução, humidade em caves, obras paradas',false),
('TIP-ED-08','Sistema construtivo','Estrutura mista (alvenaria + betão)','Rigidez incompatível, ampliações não documentadas',false),
('TIP-ED-09','Sistema construtivo','Estrutura metálica','Corrosão, ligações, pintura',false),
('TIP-ED-10','Sistema construtivo','Estrutura de madeira','Fungos, insetos, humidade',false),
('TIP-ED-11','Sistema construtivo','Pré-fabricado / pré-esforçado','Ligações, corrosão de cabos',true),
('TIP-US-01','Utilização','Uso residencial',null,false),
('TIP-US-02','Utilização','Serviços / escritórios',null,false),
('TIP-US-03','Utilização','Comercial',null,false),
('TIP-US-04','Utilização','Escolar','Em funcionamento: exige faseamento',false),
('TIP-US-05','Utilização','Hospitalar','Condicionantes de acesso e horário',false),
('TIP-US-06','Utilização','Industrial / fábrica',null,false),
('TIP-US-07','Utilização','Armazém',null,false),
('TIP-US-08','Utilização','Parque de estacionamento / caves',null,false),
('TIP-US-09','Utilização','Património classificado / de interesse',null,false),
('TIP-US-10','Utilização','Edifício em construção parado','Ex.: caves submersas',true),
('TIP-OE-01','Outras estruturas','Pontes e viadutos',null,false),
('TIP-OE-02','Outras estruturas','Muros de suporte',null,false),
('TIP-OE-03','Outras estruturas','Reservatórios e depósitos',null,false),
('TIP-OE-04','Outras estruturas','Torres e chaminés',null,false),
('TIP-OE-05','Outras estruturas','Coberturas',null,false),
('TIP-OE-06','Outras estruturas','Pavimentos industriais ou rodoviários',null,false),
('TIP-OE-07','Outras estruturas','Infraestruturas industriais',null,false),
('TIP-OE-08','Outras estruturas','Silos',null,true),
('TIP-OE-09','Outras estruturas','Túneis e estruturas enterradas',null,true),
('TIP-OE-10','Outras estruturas','Cais e estruturas marítimas',null,true)
on conflict (code) do update set category=excluded.category,name=excluded.name,notes=excluded.notes,not_in_manual=excluded.not_in_manual;

insert into kb_elements (code,name,not_in_manual) values
('ELE-01','Pilar',false),
('ELE-02','Viga',false),
('ELE-03','Laje',false),
('ELE-04','Fundações',false),
('ELE-05','Parede / alvenaria',false),
('ELE-06','Estrutura metálica',false),
('ELE-07','Cobertura',false),
('ELE-08','Pavimento de madeira',true),
('ELE-09','Escadas',true),
('ELE-10','Muro de suporte',false),
('ELE-11','Fachada / revestimento',false),
('ELE-12','Juntas',false),
('ELE-13','Varandas e consolas',true),
('ELE-14','Paredes de betão e núcleos',true),
('ELE-15','Arcos e abóbadas',true),
('ELE-16','Caves / paredes enterradas',true),
('ELE-17','Guardas e elementos não estruturais',true),
('ELE-18','Cabos e ancoragens de pré-esforço',true)
on conflict (code) do update set name=excluded.name,not_in_manual=excluded.not_in_manual;

insert into kb_causes (code,name,not_in_manual) values
('CAU-01','Carbonatação',false),
('CAU-02','Cloretos',false),
('CAU-03','Humidade / infiltração',false),
('CAU-04','Recobrimento insuficiente',false),
('CAU-05','Betão de baixa qualidade / excesso de água',false),
('CAU-06','Má compactação / falha de execução',false),
('CAU-07','Retração',false),
('CAU-08','Variações térmicas',false),
('CAU-09','Sobrecarga',false),
('CAU-10','Assentamento / recalque',false),
('CAU-11','Movimentação do terreno / nível freático',false),
('CAU-12','Ataque químico (sulfatos, ácidos)',false),
('CAU-13','Reação álcali-sílica',true),
('CAU-14','Gelo-degelo',true),
('CAU-15','Fogo',false),
('CAU-16','Impacto',false),
('CAU-17','Falta de manutenção',false),
('CAU-18','Alteração de utilização / intervenção indevida',false),
('CAU-19','Erro de projeto ou conceção',true),
('CAU-20','Sismo',true),
('CAU-21','Fadiga',false),
('CAU-22','Ataque biológico (fungos, insetos)',true),
('CAU-23','Corrosão galvânica',true),
('CAU-24','Drenagem ou impermeabilização deficiente',false),
('CAU-25','Envelhecimento natural',true),
('CAU-26','Vibrações',true),
('CAU-27','Obras vizinhas / escavações',true),
('CAU-28','Correntes vagabundas',true)
on conflict (code) do update set name=excluded.name,not_in_manual=excluded.not_in_manual;

insert into kb_solutions (code,name,not_in_manual) values
('SOL-01','Selagem',false),
('SOL-02','Injeção de resina',false),
('SOL-03','Selante flexível',false),
('SOL-04','Tratamento superficial / revestimento protetor',false),
('SOL-05','Reparação do betão (remover, limpar armaduras, recompor)',false),
('SOL-06','Proteção superficial / impregnação',true),
('SOL-07','Reforço por encamisamento',false),
('SOL-08','Reforço com compósitos (fibra de carbono ou vidro)',false),
('SOL-09','Reforço com chapas ou perfis metálicos',false),
('SOL-10','Substituição ou complemento de armadura',false),
('SOL-11','Proteção catódica',true),
('SOL-12','Extração de cloretos / realcalinização',true),
('SOL-13','Impermeabilização',false),
('SOL-14','Reparação de juntas',false),
('SOL-15','Melhoria de drenagem',false),
('SOL-16','Corrigir a origem da infiltração',false),
('SOL-17','Reforço ou recalçamento de fundações',true),
('SOL-18','Injeção de consolidação em alvenarias',true),
('SOL-19','Cosedura, tirantes e atirantamento',true),
('SOL-20','Reparação de alvenaria (refechamento, substituição)',false),
('SOL-21','Tratamento anticorrosivo e pintura (metal)',false),
('SOL-22','Substituição de elementos ou ligações',false),
('SOL-23','Reparação de soldaduras',false),
('SOL-24','Tratamento e reforço de madeira',true),
('SOL-25','Redução de cargas / escoramento provisório',false),
('SOL-26','Monitorização',false),
('SOL-27','Substituição do elemento',false),
('SOL-28','Investigação adicional',false),
('SOL-29','Isolar a área / medidas de segurança imediatas',false),
('SOL-30','Manutenção e limpeza',false)
on conflict (code) do update set name=excluded.name,not_in_manual=excluded.not_in_manual;

insert into kb_client_info_items (code,name,not_in_manual) values
('INF-01','Nome da empresa / cliente',false),
('INF-02','Localização',false),
('INF-03','Tipo de estrutura',false),
('INF-04','Área aproximada',false),
('INF-05','Número de pisos',false),
('INF-06','Idade da estrutura',false),
('INF-07','Plantas',false),
('INF-08','Projeto estrutural',false),
('INF-09','Problemas identificados',false),
('INF-10','Fotografias existentes',false),
('INF-11','Histórico de reparações',false),
('INF-12','Motivo do diagnóstico',false),
('INF-13','Prazo pretendido',false),
('INF-14','Necessidade de relatório',false),
('INF-15','Necessidade de ensaios',false),
('INF-16','Necessidade de reparação',false),
('INF-17','Necessidade de monitorização',false),
('INF-18','Acesso ao local e horários',true),
('INF-19','Estudo geotécnico',true),
('INF-20','Ocupação do edifício / condicionantes',true),
('INF-21','Licenças e autorizações',true),
('INF-22','Relatórios anteriores',true),
('INF-23','Histórico de infiltrações e acidentes',true),
('INF-24','Contacto do dono de obra',true)
on conflict (code) do update set name=excluded.name,not_in_manual=excluded.not_in_manual;

insert into kb_severity (level,name,meaning,action) values
(1,'Baixa','Superficial, sem comprometimento estrutural imediato','Manutenção e acompanhamento'),
(2,'Média','Pode evoluir e afetar a durabilidade','Reparação programada e monitorização'),
(3,'Alta','Relevante em elemento estrutural','Avaliação detalhada e intervenção prioritária'),
(4,'Crítica','Sinais de possível instabilidade ou risco significativo','Proteger/isolar a área e avaliar urgentemente')
on conflict (level) do update set name=excluded.name,meaning=excluded.meaning,action=excluded.action;

insert into kb_tests (code,name,test_group,service_id,not_in_manual) values
('ENS-01','Inspeção visual (inclui martelo de inspeção)','Inspeção',null,false),
('ENS-02','Levantamento dimensional / geométrico','Inspeção',null,false),
('ENS-03','Mapeamento de fissuras','Inspeção',null,false),
('ENS-04','Medição da abertura de fissuras','Inspeção',null,false),
('ENS-05','Monitorização com fissurómetro','Monitorização','FISS_M1',false),
('ENS-06','Nivelamento e estação total','Inspeção',null,false),
('ENS-07','Nuvem de pontos / laser scanner','Inspeção',null,true),
('ENS-08','Inspeção por drone','Inspeção',null,false),
('ENS-10','Esclerometria (NP EN 12504-2)','Betão',null,false),
('ENS-11','Ultrassons (NP EN 12504-4)','Betão',null,false),
('ENS-12','Pacometria / deteção de armaduras e recobrimento','Betão','PACO',false),
('ENS-13','Georradar','Betão',null,true),
('ENS-14','Potencial de corrosão, half-cell (ASTM C876)','Betão',null,true),
('ENS-15','Resistividade elétrica','Betão',null,true),
('ENS-16','Profundidade de carbonatação (fenolftaleína)','Betão','CARB',false),
('ENS-17','Teor de cloretos por perfis de profundidade','Betão','CLOR',false),
('ENS-18','Carotes e resistência à compressão (NP EN 12504-1, NP EN 13791)','Betão','CAROTE',false),
('ENS-19','Arrancamento / pull-off','Betão',null,true),
('ENS-20','Ensaios de tração e análise de armaduras','Betão',null,true),
('ENS-21','Petrografia / diagnóstico de RAS','Betão',null,true),
('ENS-22','Absorção de água','Betão',null,true),
('ENS-23','Prova de carga','Estrutura',null,true),
('ENS-30','Medição de humidade','Humidade',null,false),
('ENS-31','Termografia','Humidade',null,false),
('ENS-40','Macacos planos, simples e duplos','Alvenaria','MACACO',false),
('ENS-41','Ensaios sónicos / ultrassons em alvenaria','Alvenaria',null,true),
('ENS-42','Endoscopia','Alvenaria',null,true),
('ENS-43','Sondagens de inspeção e janelas de observação','Alvenaria',null,true),
('ENS-50','Resistografia','Madeira','RESIST',false),
('ENS-51','Ultrassons e humidade em madeira','Madeira',null,true),
('ENS-60','Medição de espessura por ultrassons','Metal',null,true),
('ENS-61','Líquidos penetrantes / partículas magnéticas / soldaduras','Metal',null,true),
('ENS-70','Prospeção geotécnica (SPT, CPT, sondagens)','Geotecnia',null,true),
('ENS-71','Poços de reconhecimento de fundações','Geotecnia',null,true),
('ENS-72','Piezómetros','Geotecnia',null,true),
('ENS-80','Extensómetros / deformímetros','Monitorização',null,true),
('ENS-81','Clinómetros / inclinómetros','Monitorização',null,true),
('ENS-82','Sensores de humidade e temperatura','Monitorização',null,true),
('ENS-83','Monitorização de vibrações','Monitorização',null,true)
on conflict (code) do update set name=excluded.name,test_group=excluded.test_group,service_id=excluded.service_id,not_in_manual=excluded.not_in_manual;

insert into kb_pathology_groups (code,name) values
('BA','Betão armado'),
('PE','Betão pré-esforçado'),
('AL','Alvenaria'),
('FU','Fundações e terreno'),
('HU','Água e humidade'),
('ME','Estruturas metálicas'),
('MA','Madeira'),
('OU','Outros e transversais')
on conflict (code) do update set name=excluded.name;

insert into kb_pathologies (code,group_code,name,sev_min,sev_max,not_in_manual) values
('PAT-BA-001','BA','Fissura vertical',1,2,false),
('PAT-BA-002','BA','Fissura horizontal',2,2,false),
('PAT-BA-003','BA','Fissura diagonal',3,3,false),
('PAT-BA-004','BA','Fissura em mapa',1,2,false),
('PAT-BA-005','BA','Rachadura profunda / passante',3,4,false),
('PAT-BA-006','BA','Fissura de flexão (viga/laje)',2,3,true),
('PAT-BA-007','BA','Fissura de corte (viga)',3,4,false),
('PAT-BA-008','BA','Fissura longitudinal ao longo da armadura',2,3,false),
('PAT-BA-009','BA','Fissura de retração ou assentamento plástico',1,1,true),
('PAT-BA-010','BA','Fissura térmica',1,2,true),
('PAT-BA-011','BA','Fissuração por RAS',2,3,true),
('PAT-BA-012','BA','Punçoamento / torção em laje-pilar',3,4,true),
('PAT-BA-020','BA','Desagregação',2,3,false),
('PAT-BA-021','BA','Destacamento do betão',3,3,false),
('PAT-BA-022','BA','Delaminação',2,2,true),
('PAT-BA-023','BA','Esmagamento (pilar)',4,4,false),
('PAT-BA-024','BA','Bicheiras / ninhos de brita',1,2,true),
('PAT-BA-025','BA','Segregação',2,2,true),
('PAT-BA-026','BA','Perda de secção do betão',3,3,false),
('PAT-BA-030','BA','Armaduras expostas',2,3,false),
('PAT-BA-031','BA','Corrosão por carbonatação',2,3,false),
('PAT-BA-032','BA','Corrosão por cloretos',3,3,false),
('PAT-BA-033','BA','Redução da secção da armadura',3,4,false),
('PAT-BA-034','BA','Corrosão por correntes vagabundas',3,3,true),
('PAT-BA-035','BA','Manchas de ferrugem / expansão do betão',2,2,false),
('PAT-BA-040','BA','Eflorescências',1,1,false),
('PAT-BA-041','BA','Lixiviação',2,2,true),
('PAT-BA-042','BA','Ataque por sulfatos ou ácidos',2,3,true),
('PAT-BA-043','BA','Gelo-degelo',1,2,true),
('PAT-BA-044','BA','Carbonatação atingindo a armadura',2,2,false),
('PAT-BA-045','BA','Contaminação por cloretos',3,3,false),
('PAT-BA-050','BA','Deformação / flecha excessiva',2,3,false),
('PAT-BA-051','BA','Desaprumo / inclinação de pilares',3,3,false),
('PAT-BA-052','BA','Danos por fogo',3,3,true),
('PAT-BA-053','BA','Danos por impacto',2,3,false),
('PAT-BA-054','BA','Betão com resistência inferior à de projeto',3,3,true),
('PAT-BA-055','BA','Armadura insuficiente ou mal posicionada',3,3,true),
('PAT-BA-056','BA','Recobrimento insuficiente',2,2,false),
('PAT-BA-057','BA','Junta de betonagem deficiente',2,2,true),
('PAT-BA-058','BA','Degradação de varandas e consolas',3,4,true),
('PAT-BA-059','BA','Degradação de juntas de dilatação',1,2,true),
('PAT-BA-060','BA','Betão exposto a água / submersão prolongada',2,3,true),
('PAT-BA-061','BA','Sobrecarga',3,3,false),
('PAT-PE-001','PE','Corrosão de cabos / bainhas',4,4,true),
('PAT-PE-002','PE','Perda de pré-esforço',3,4,true),
('PAT-PE-003','PE','Injeção deficiente de bainhas',3,3,true),
('PAT-PE-004','PE','Rotura de fios ou ancoragens',4,4,true),
('PAT-AL-001','AL','Fissuras verticais em paredes',1,2,false),
('PAT-AL-002','AL','Fissuras diagonais / em cunhais',3,3,false),
('PAT-AL-003','AL','Fissuras horizontais / esmagamento',3,3,false),
('PAT-AL-004','AL','Fissuras em torno de vãos',2,2,true),
('PAT-AL-005','AL','Desaprumo / encurvadura de parede',3,4,false),
('PAT-AL-006','AL','Desligamento entre paredes ou parede–pavimento',3,3,true),
('PAT-AL-007','AL','Perda de argamassa das juntas',2,2,true),
('PAT-AL-008','AL','Desagregação da pedra ou do tijolo',2,2,true),
('PAT-AL-009','AL','Destacamento de revestimentos (reboco, azulejo)',2,2,false),
('PAT-AL-010','AL','Descolamento / desalinhamento de revestimento pétreo',2,3,true),
('PAT-AL-011','AL','Vazios / heterogeneidade em paredes de pedra',2,3,true),
('PAT-AL-012','AL','Degradação de arcos e abóbadas',3,3,true),
('PAT-AL-013','AL','Deformações de paredes',2,3,false),
('PAT-AL-014','AL','Remoção ou alteração indevida de paredes resistentes',3,4,true),
('PAT-FU-001','FU','Assentamento uniforme',1,2,false),
('PAT-FU-002','FU','Recalque diferencial',3,3,false),
('PAT-FU-003','FU','Rotação / inclinação da estrutura',3,4,false),
('PAT-FU-004','FU','Desnivelamento de pavimentos',2,2,false),
('PAT-FU-005','FU','Movimentação do terreno (deslizamento, argilas expansivas)',3,3,true),
('PAT-FU-006','FU','Variação do nível freático / inundação de caves',2,3,true),
('PAT-FU-007','FU','Subescavação / erosão',3,3,true),
('PAT-FU-008','FU','Fundações insuficientes ou degradadas',3,3,true),
('PAT-FU-009','FU','Danos por obras vizinhas',2,3,true),
('PAT-HU-001','HU','Infiltração em coberturas e terraços',2,2,false),
('PAT-HU-002','HU','Infiltração em fachadas e juntas',2,2,false),
('PAT-HU-003','HU','Infiltração de casas de banho e tubagens',2,2,false),
('PAT-HU-004','HU','Infiltração em caves e paredes enterradas',2,3,true),
('PAT-HU-005','HU','Perda de estanquidade em reservatórios',3,3,false),
('PAT-HU-006','HU','Condensações e pontes térmicas',1,1,true),
('PAT-HU-007','HU','Bolores',1,1,false),
('PAT-HU-008','HU','Drenagem deficiente',2,2,false),
('PAT-HU-009','HU','Humidade ascensional',2,2,true),
('PAT-HU-010','HU','Cristalização de sais',2,2,true),
('PAT-ME-001','ME','Corrosão generalizada',2,3,false),
('PAT-ME-002','ME','Corrosão localizada (picadas, frestas)',2,3,true),
('PAT-ME-003','ME','Perda de espessura',3,3,false),
('PAT-ME-004','ME','Deformação',2,3,false),
('PAT-ME-005','ME','Encurvadura local ou global',3,4,true),
('PAT-ME-006','ME','Defeitos e fissuras em soldaduras',3,3,false),
('PAT-ME-007','ME','Parafusos soltos, corroídos ou em falta',2,3,false),
('PAT-ME-008','ME','Ligações danificadas',3,3,false),
('PAT-ME-009','ME','Falha da pintura de proteção',1,2,false),
('PAT-ME-010','ME','Fadiga e fissuras',3,4,false),
('PAT-ME-011','ME','Danos por fogo',3,3,true),
('PAT-MA-001','MA','Podridão fúngica',3,3,true),
('PAT-MA-002','MA','Ataque de insetos de ciclo larvar (carunchos)',2,3,true),
('PAT-MA-003','MA','Ataque de térmitas',3,3,true),
('PAT-MA-004','MA','Apodrecimento de topos de vigas embebidos',3,3,true),
('PAT-MA-005','MA','Perda de secção da madeira',3,3,true),
('PAT-MA-006','MA','Flecha excessiva em pavimentos',2,3,true),
('PAT-MA-007','MA','Fendas e empenos',1,2,true),
('PAT-MA-008','MA','Ligações deficientes ou desligadas',3,3,true),
('PAT-MA-009','MA','Elementos removidos ou alterados na gaiola',3,4,true),
('PAT-OU-001','OU','Deformação da estrutura de cobertura',2,3,false),
('PAT-OU-002','OU','Degradação de pavimentos industriais ou rodoviários',2,2,false),
('PAT-OU-003','OU','Muro de suporte: tombamento, deslizamento, drenagem',3,3,true),
('PAT-OU-004','OU','Pontes: degradação de apoios, juntas ou tabuleiro',2,4,true),
('PAT-OU-005','OU','Torres e chaminés: inclinação e fissuras',3,3,true),
('PAT-OU-006','OU','Alteração de utilização / sobrecarga',3,3,false),
('PAT-OU-007','OU','Intervenções não documentadas',2,4,false),
('PAT-OU-008','OU','Danos sísmicos',3,4,true),
('PAT-OU-009','OU','Falta de manutenção / envelhecimento',1,2,false),
('PAT-OU-010','OU','Vibrações',2,2,true)
on conflict (code) do update set group_code=excluded.group_code,name=excluded.name,sev_min=excluded.sev_min,sev_max=excluded.sev_max,not_in_manual=excluded.not_in_manual;

insert into kb_pathology_causes (pathology_code,cause_code) values
('PAT-BA-001','CAU-07'),
('PAT-BA-001','CAU-10'),
('PAT-BA-002','CAU-01'),
('PAT-BA-002','CAU-02'),
('PAT-BA-002','CAU-09'),
('PAT-BA-003','CAU-09'),
('PAT-BA-003','CAU-10'),
('PAT-BA-004','CAU-05'),
('PAT-BA-004','CAU-07'),
('PAT-BA-004','CAU-13'),
('PAT-BA-005','CAU-09'),
('PAT-BA-005','CAU-10'),
('PAT-BA-005','CAU-11'),
('PAT-BA-006','CAU-09'),
('PAT-BA-006','CAU-19'),
('PAT-BA-007','CAU-09'),
('PAT-BA-007','CAU-19'),
('PAT-BA-008','CAU-01'),
('PAT-BA-008','CAU-02'),
('PAT-BA-009','CAU-06'),
('PAT-BA-009','CAU-07'),
('PAT-BA-010','CAU-08'),
('PAT-BA-011','CAU-13'),
('PAT-BA-012','CAU-09'),
('PAT-BA-012','CAU-19'),
('PAT-BA-020','CAU-03'),
('PAT-BA-020','CAU-05'),
('PAT-BA-020','CAU-06'),
('PAT-BA-020','CAU-12'),
('PAT-BA-021','CAU-01'),
('PAT-BA-021','CAU-02'),
('PAT-BA-021','CAU-15'),
('PAT-BA-022','CAU-01'),
('PAT-BA-022','CAU-02'),
('PAT-BA-023','CAU-05'),
('PAT-BA-023','CAU-09'),
('PAT-BA-024','CAU-06'),
('PAT-BA-025','CAU-05'),
('PAT-BA-025','CAU-06'),
('PAT-BA-026','CAU-01'),
('PAT-BA-026','CAU-02'),
('PAT-BA-026','CAU-12'),
('PAT-BA-030','CAU-04'),
('PAT-BA-030','CAU-01'),
('PAT-BA-030','CAU-02'),
('PAT-BA-031','CAU-01'),
('PAT-BA-031','CAU-03'),
('PAT-BA-031','CAU-04'),
('PAT-BA-032','CAU-02'),
('PAT-BA-033','CAU-01'),
('PAT-BA-033','CAU-02'),
('PAT-BA-034','CAU-28'),
('PAT-BA-035','CAU-01'),
('PAT-BA-035','CAU-02'),
('PAT-BA-040','CAU-03'),
('PAT-BA-041','CAU-03'),
('PAT-BA-041','CAU-12'),
('PAT-BA-042','CAU-12'),
('PAT-BA-043','CAU-14'),
('PAT-BA-044','CAU-01'),
('PAT-BA-044','CAU-04'),
('PAT-BA-045','CAU-02'),
('PAT-BA-050','CAU-09'),
('PAT-BA-050','CAU-07'),
('PAT-BA-051','CAU-10'),
('PAT-BA-051','CAU-20'),
('PAT-BA-052','CAU-15'),
('PAT-BA-053','CAU-16'),
('PAT-BA-054','CAU-05'),
('PAT-BA-054','CAU-19'),
('PAT-BA-055','CAU-06'),
('PAT-BA-055','CAU-19'),
('PAT-BA-056','CAU-04'),
('PAT-BA-056','CAU-06'),
('PAT-BA-057','CAU-06'),
('PAT-BA-058','CAU-01'),
('PAT-BA-058','CAU-02'),
('PAT-BA-058','CAU-03'),
('PAT-BA-059','CAU-08'),
('PAT-BA-059','CAU-17'),
('PAT-BA-060','CAU-03'),
('PAT-BA-060','CAU-11'),
('PAT-BA-060','CAU-24'),
('PAT-BA-061','CAU-09'),
('PAT-BA-061','CAU-18'),
('PAT-PE-001','CAU-02'),
('PAT-PE-001','CAU-03'),
('PAT-PE-002','CAU-25'),
('PAT-PE-002','CAU-09'),
('PAT-PE-003','CAU-06'),
('PAT-PE-004','CAU-02'),
('PAT-PE-004','CAU-21'),
('PAT-AL-001','CAU-07'),
('PAT-AL-001','CAU-08'),
('PAT-AL-001','CAU-10'),
('PAT-AL-002','CAU-10'),
('PAT-AL-002','CAU-20'),
('PAT-AL-003','CAU-09'),
('PAT-AL-004','CAU-19'),
('PAT-AL-004','CAU-18'),
('PAT-AL-005','CAU-09'),
('PAT-AL-005','CAU-10'),
('PAT-AL-005','CAU-20'),
('PAT-AL-006','CAU-20'),
('PAT-AL-006','CAU-18'),
('PAT-AL-007','CAU-03'),
('PAT-AL-007','CAU-25'),
('PAT-AL-008','CAU-03'),
('PAT-AL-008','CAU-12'),
('PAT-AL-009','CAU-03'),
('PAT-AL-009','CAU-08'),
('PAT-AL-010','CAU-08'),
('PAT-AL-010','CAU-03'),
('PAT-AL-010','CAU-10'),
('PAT-AL-011','CAU-25'),
('PAT-AL-012','CAU-09'),
('PAT-AL-012','CAU-10'),
('PAT-AL-013','CAU-09'),
('PAT-AL-013','CAU-10'),
('PAT-AL-014','CAU-18'),
('PAT-FU-001','CAU-10'),
('PAT-FU-002','CAU-10'),
('PAT-FU-002','CAU-11'),
('PAT-FU-003','CAU-10'),
('PAT-FU-003','CAU-11'),
('PAT-FU-004','CAU-10'),
('PAT-FU-005','CAU-11'),
('PAT-FU-006','CAU-11'),
('PAT-FU-006','CAU-24'),
('PAT-FU-007','CAU-11'),
('PAT-FU-007','CAU-27'),
('PAT-FU-008','CAU-19'),
('PAT-FU-008','CAU-25'),
('PAT-FU-009','CAU-27'),
('PAT-FU-009','CAU-26'),
('PAT-HU-001','CAU-03'),
('PAT-HU-001','CAU-24'),
('PAT-HU-002','CAU-03'),
('PAT-HU-002','CAU-24'),
('PAT-HU-003','CAU-03'),
('PAT-HU-004','CAU-03'),
('PAT-HU-004','CAU-11'),
('PAT-HU-004','CAU-24'),
('PAT-HU-005','CAU-03'),
('PAT-HU-005','CAU-07'),
('PAT-HU-006','CAU-08'),
('PAT-HU-007','CAU-03'),
('PAT-HU-008','CAU-24'),
('PAT-HU-009','CAU-03'),
('PAT-HU-009','CAU-11'),
('PAT-HU-010','CAU-03'),
('PAT-ME-001','CAU-03'),
('PAT-ME-001','CAU-17'),
('PAT-ME-002','CAU-03'),
('PAT-ME-002','CAU-23'),
('PAT-ME-003','CAU-03'),
('PAT-ME-003','CAU-17'),
('PAT-ME-004','CAU-09'),
('PAT-ME-005','CAU-09'),
('PAT-ME-006','CAU-21'),
('PAT-ME-006','CAU-06'),
('PAT-ME-007','CAU-17'),
('PAT-ME-007','CAU-03'),
('PAT-ME-008','CAU-09'),
('PAT-ME-008','CAU-21'),
('PAT-ME-009','CAU-17'),
('PAT-ME-010','CAU-21'),
('PAT-ME-011','CAU-15'),
('PAT-MA-001','CAU-22'),
('PAT-MA-001','CAU-03'),
('PAT-MA-002','CAU-22'),
('PAT-MA-003','CAU-22'),
('PAT-MA-004','CAU-22'),
('PAT-MA-004','CAU-03'),
('PAT-MA-005','CAU-22'),
('PAT-MA-005','CAU-25'),
('PAT-MA-006','CAU-09'),
('PAT-MA-006','CAU-25'),
('PAT-MA-007','CAU-08'),
('PAT-MA-007','CAU-25'),
('PAT-MA-008','CAU-20'),
('PAT-MA-008','CAU-25'),
('PAT-MA-009','CAU-18'),
('PAT-OU-001','CAU-09'),
('PAT-OU-001','CAU-03'),
('PAT-OU-002','CAU-09'),
('PAT-OU-002','CAU-26'),
('PAT-OU-003','CAU-10'),
('PAT-OU-003','CAU-11'),
('PAT-OU-003','CAU-24'),
('PAT-OU-004','CAU-17'),
('PAT-OU-004','CAU-21'),
('PAT-OU-004','CAU-02'),
('PAT-OU-005','CAU-08'),
('PAT-OU-005','CAU-10'),
('PAT-OU-005','CAU-20'),
('PAT-OU-006','CAU-18'),
('PAT-OU-006','CAU-09'),
('PAT-OU-007','CAU-18'),
('PAT-OU-008','CAU-20'),
('PAT-OU-009','CAU-17'),
('PAT-OU-009','CAU-25'),
('PAT-OU-010','CAU-26')
on conflict do nothing;

insert into kb_pathology_tests (pathology_code,test_code) values
('PAT-BA-001','ENS-03'),
('PAT-BA-001','ENS-04'),
('PAT-BA-001','ENS-05'),
('PAT-BA-002','ENS-03'),
('PAT-BA-002','ENS-12'),
('PAT-BA-002','ENS-16'),
('PAT-BA-003','ENS-03'),
('PAT-BA-003','ENS-05'),
('PAT-BA-003','ENS-06'),
('PAT-BA-004','ENS-03'),
('PAT-BA-004','ENS-21'),
('PAT-BA-005','ENS-03'),
('PAT-BA-005','ENS-05'),
('PAT-BA-005','ENS-06'),
('PAT-BA-005','ENS-11'),
('PAT-BA-006','ENS-03'),
('PAT-BA-006','ENS-06'),
('PAT-BA-006','ENS-23'),
('PAT-BA-007','ENS-03'),
('PAT-BA-007','ENS-12'),
('PAT-BA-007','ENS-23'),
('PAT-BA-008','ENS-12'),
('PAT-BA-008','ENS-14'),
('PAT-BA-008','ENS-16'),
('PAT-BA-008','ENS-17'),
('PAT-BA-009','ENS-03'),
('PAT-BA-009','ENS-04'),
('PAT-BA-010','ENS-03'),
('PAT-BA-010','ENS-05'),
('PAT-BA-011','ENS-21'),
('PAT-BA-011','ENS-10'),
('PAT-BA-012','ENS-03'),
('PAT-BA-012','ENS-06'),
('PAT-BA-012','ENS-23'),
('PAT-BA-020','ENS-10'),
('PAT-BA-020','ENS-11'),
('PAT-BA-020','ENS-18'),
('PAT-BA-021','ENS-01'),
('PAT-BA-021','ENS-12'),
('PAT-BA-021','ENS-16'),
('PAT-BA-021','ENS-17'),
('PAT-BA-022','ENS-01'),
('PAT-BA-022','ENS-11'),
('PAT-BA-023','ENS-10'),
('PAT-BA-023','ENS-11'),
('PAT-BA-023','ENS-18'),
('PAT-BA-024','ENS-11'),
('PAT-BA-024','ENS-18'),
('PAT-BA-025','ENS-11'),
('PAT-BA-025','ENS-18'),
('PAT-BA-026','ENS-02'),
('PAT-BA-026','ENS-12'),
('PAT-BA-030','ENS-01'),
('PAT-BA-030','ENS-12'),
('PAT-BA-030','ENS-16'),
('PAT-BA-031','ENS-12'),
('PAT-BA-031','ENS-14'),
('PAT-BA-031','ENS-16'),
('PAT-BA-032','ENS-14'),
('PAT-BA-032','ENS-17'),
('PAT-BA-033','ENS-01'),
('PAT-BA-033','ENS-20'),
('PAT-BA-034','ENS-14'),
('PAT-BA-034','ENS-15'),
('PAT-BA-035','ENS-01'),
('PAT-BA-035','ENS-12'),
('PAT-BA-040','ENS-30'),
('PAT-BA-041','ENS-22'),
('PAT-BA-042','ENS-18'),
('PAT-BA-042','ENS-21'),
('PAT-BA-043','ENS-01'),
('PAT-BA-043','ENS-22'),
('PAT-BA-044','ENS-12'),
('PAT-BA-044','ENS-16'),
('PAT-BA-045','ENS-17'),
('PAT-BA-045','ENS-14'),
('PAT-BA-050','ENS-06'),
('PAT-BA-050','ENS-23'),
('PAT-BA-051','ENS-06'),
('PAT-BA-051','ENS-81'),
('PAT-BA-052','ENS-10'),
('PAT-BA-052','ENS-11'),
('PAT-BA-052','ENS-18'),
('PAT-BA-052','ENS-20'),
('PAT-BA-053','ENS-01'),
('PAT-BA-053','ENS-11'),
('PAT-BA-054','ENS-10'),
('PAT-BA-054','ENS-11'),
('PAT-BA-054','ENS-18'),
('PAT-BA-055','ENS-12'),
('PAT-BA-055','ENS-13'),
('PAT-BA-056','ENS-12'),
('PAT-BA-057','ENS-11'),
('PAT-BA-057','ENS-43'),
('PAT-BA-058','ENS-01'),
('PAT-BA-058','ENS-12'),
('PAT-BA-058','ENS-16'),
('PAT-BA-058','ENS-17'),
('PAT-BA-059','ENS-01'),
('PAT-BA-060','ENS-12'),
('PAT-BA-060','ENS-16'),
('PAT-BA-060','ENS-17'),
('PAT-BA-060','ENS-18'),
('PAT-BA-061','ENS-06'),
('PAT-BA-061','ENS-23'),
('PAT-PE-001','ENS-13'),
('PAT-PE-001','ENS-42'),
('PAT-PE-002','ENS-06'),
('PAT-PE-002','ENS-80'),
('PAT-PE-003','ENS-13'),
('PAT-PE-003','ENS-42'),
('PAT-PE-004','ENS-13'),
('PAT-PE-004','ENS-42'),
('PAT-AL-001','ENS-03'),
('PAT-AL-001','ENS-05'),
('PAT-AL-002','ENS-03'),
('PAT-AL-002','ENS-05'),
('PAT-AL-002','ENS-06'),
('PAT-AL-003','ENS-03'),
('PAT-AL-003','ENS-40'),
('PAT-AL-004','ENS-03'),
('PAT-AL-005','ENS-06'),
('PAT-AL-006','ENS-01'),
('PAT-AL-006','ENS-03'),
('PAT-AL-007','ENS-01'),
('PAT-AL-008','ENS-01'),
('PAT-AL-008','ENS-41'),
('PAT-AL-009','ENS-01'),
('PAT-AL-009','ENS-31'),
('PAT-AL-010','ENS-03'),
('PAT-AL-010','ENS-05'),
('PAT-AL-010','ENS-06'),
('PAT-AL-011','ENS-40'),
('PAT-AL-011','ENS-41'),
('PAT-AL-011','ENS-42'),
('PAT-AL-011','ENS-43'),
('PAT-AL-012','ENS-06'),
('PAT-AL-012','ENS-42'),
('PAT-AL-013','ENS-06'),
('PAT-AL-014','ENS-01'),
('PAT-AL-014','ENS-43'),
('PAT-FU-001','ENS-06'),
('PAT-FU-001','ENS-70'),
('PAT-FU-002','ENS-05'),
('PAT-FU-002','ENS-06'),
('PAT-FU-002','ENS-70'),
('PAT-FU-002','ENS-71'),
('PAT-FU-003','ENS-06'),
('PAT-FU-003','ENS-81'),
('PAT-FU-004','ENS-06'),
('PAT-FU-005','ENS-70'),
('PAT-FU-005','ENS-81'),
('PAT-FU-006','ENS-72'),
('PAT-FU-007','ENS-71'),
('PAT-FU-007','ENS-70'),
('PAT-FU-008','ENS-71'),
('PAT-FU-008','ENS-70'),
('PAT-FU-009','ENS-05'),
('PAT-FU-009','ENS-80'),
('PAT-FU-009','ENS-83'),
('PAT-HU-001','ENS-30'),
('PAT-HU-001','ENS-31'),
('PAT-HU-002','ENS-30'),
('PAT-HU-002','ENS-31'),
('PAT-HU-003','ENS-30'),
('PAT-HU-003','ENS-31'),
('PAT-HU-004','ENS-30'),
('PAT-HU-005','ENS-30'),
('PAT-HU-006','ENS-31'),
('PAT-HU-007','ENS-30'),
('PAT-HU-008','ENS-01'),
('PAT-HU-009','ENS-30'),
('PAT-HU-009','ENS-31'),
('PAT-HU-010','ENS-30'),
('PAT-ME-001','ENS-01'),
('PAT-ME-001','ENS-60'),
('PAT-ME-002','ENS-01'),
('PAT-ME-002','ENS-60'),
('PAT-ME-003','ENS-60'),
('PAT-ME-004','ENS-06'),
('PAT-ME-005','ENS-06'),
('PAT-ME-006','ENS-61'),
('PAT-ME-007','ENS-01'),
('PAT-ME-008','ENS-01'),
('PAT-ME-008','ENS-61'),
('PAT-ME-009','ENS-01'),
('PAT-ME-010','ENS-61'),
('PAT-ME-011','ENS-01'),
('PAT-ME-011','ENS-60'),
('PAT-MA-001','ENS-50'),
('PAT-MA-001','ENS-51'),
('PAT-MA-002','ENS-50'),
('PAT-MA-002','ENS-01'),
('PAT-MA-003','ENS-50'),
('PAT-MA-003','ENS-01'),
('PAT-MA-004','ENS-50'),
('PAT-MA-005','ENS-50'),
('PAT-MA-006','ENS-06'),
('PAT-MA-006','ENS-50'),
('PAT-MA-007','ENS-01'),
('PAT-MA-008','ENS-01'),
('PAT-MA-009','ENS-01'),
('PAT-MA-009','ENS-43'),
('PAT-OU-001','ENS-06'),
('PAT-OU-002','ENS-01'),
('PAT-OU-002','ENS-11'),
('PAT-OU-003','ENS-06'),
('PAT-OU-003','ENS-81'),
('PAT-OU-004','ENS-01'),
('PAT-OU-004','ENS-14'),
('PAT-OU-004','ENS-17'),
('PAT-OU-005','ENS-06'),
('PAT-OU-005','ENS-81'),
('PAT-OU-005','ENS-03'),
('PAT-OU-006','ENS-06'),
('PAT-OU-006','ENS-23'),
('PAT-OU-007','ENS-01'),
('PAT-OU-007','ENS-43'),
('PAT-OU-008','ENS-03'),
('PAT-OU-008','ENS-06'),
('PAT-OU-009','ENS-01'),
('PAT-OU-010','ENS-83')
on conflict do nothing;

insert into kb_pathology_solutions (pathology_code,solution_code) values
('PAT-BA-001','SOL-01'),
('PAT-BA-001','SOL-02'),
('PAT-BA-001','SOL-26'),
('PAT-BA-002','SOL-02'),
('PAT-BA-002','SOL-05'),
('PAT-BA-003','SOL-02'),
('PAT-BA-003','SOL-08'),
('PAT-BA-003','SOL-26'),
('PAT-BA-004','SOL-04'),
('PAT-BA-005','SOL-25'),
('PAT-BA-005','SOL-26'),
('PAT-BA-005','SOL-08'),
('PAT-BA-006','SOL-02'),
('PAT-BA-006','SOL-08'),
('PAT-BA-006','SOL-09'),
('PAT-BA-007','SOL-08'),
('PAT-BA-007','SOL-09'),
('PAT-BA-007','SOL-25'),
('PAT-BA-008','SOL-05'),
('PAT-BA-009','SOL-01'),
('PAT-BA-009','SOL-04'),
('PAT-BA-010','SOL-03'),
('PAT-BA-011','SOL-04'),
('PAT-BA-011','SOL-26'),
('PAT-BA-012','SOL-08'),
('PAT-BA-012','SOL-09'),
('PAT-BA-012','SOL-25'),
('PAT-BA-012','SOL-29'),
('PAT-BA-020','SOL-05'),
('PAT-BA-020','SOL-07'),
('PAT-BA-021','SOL-05'),
('PAT-BA-022','SOL-05'),
('PAT-BA-023','SOL-25'),
('PAT-BA-023','SOL-29'),
('PAT-BA-023','SOL-07'),
('PAT-BA-023','SOL-08'),
('PAT-BA-023','SOL-09'),
('PAT-BA-024','SOL-05'),
('PAT-BA-025','SOL-05'),
('PAT-BA-026','SOL-05'),
('PAT-BA-026','SOL-07'),
('PAT-BA-030','SOL-05'),
('PAT-BA-031','SOL-05'),
('PAT-BA-031','SOL-06'),
('PAT-BA-032','SOL-05'),
('PAT-BA-032','SOL-11'),
('PAT-BA-032','SOL-12'),
('PAT-BA-033','SOL-10'),
('PAT-BA-033','SOL-08'),
('PAT-BA-034','SOL-11'),
('PAT-BA-035','SOL-05'),
('PAT-BA-040','SOL-13'),
('PAT-BA-040','SOL-16'),
('PAT-BA-041','SOL-04'),
('PAT-BA-041','SOL-13'),
('PAT-BA-042','SOL-05'),
('PAT-BA-042','SOL-07'),
('PAT-BA-043','SOL-04'),
('PAT-BA-044','SOL-05'),
('PAT-BA-044','SOL-06'),
('PAT-BA-044','SOL-12'),
('PAT-BA-045','SOL-05'),
('PAT-BA-045','SOL-11'),
('PAT-BA-045','SOL-12'),
('PAT-BA-050','SOL-25'),
('PAT-BA-050','SOL-08'),
('PAT-BA-050','SOL-09'),
('PAT-BA-051','SOL-25'),
('PAT-BA-051','SOL-26'),
('PAT-BA-052','SOL-05'),
('PAT-BA-052','SOL-07'),
('PAT-BA-052','SOL-08'),
('PAT-BA-053','SOL-05'),
('PAT-BA-053','SOL-08'),
('PAT-BA-054','SOL-07'),
('PAT-BA-054','SOL-08'),
('PAT-BA-055','SOL-07'),
('PAT-BA-055','SOL-08'),
('PAT-BA-055','SOL-09'),
('PAT-BA-056','SOL-05'),
('PAT-BA-056','SOL-06'),
('PAT-BA-057','SOL-02'),
('PAT-BA-058','SOL-29'),
('PAT-BA-058','SOL-05'),
('PAT-BA-058','SOL-08'),
('PAT-BA-059','SOL-14'),
('PAT-BA-060','SOL-05'),
('PAT-BA-060','SOL-13'),
('PAT-BA-060','SOL-15'),
('PAT-BA-061','SOL-25'),
('PAT-BA-061','SOL-08'),
('PAT-BA-061','SOL-09'),
('PAT-PE-001','SOL-25'),
('PAT-PE-001','SOL-29'),
('PAT-PE-001','SOL-28'),
('PAT-PE-002','SOL-28'),
('PAT-PE-002','SOL-08'),
('PAT-PE-003','SOL-28'),
('PAT-PE-004','SOL-25'),
('PAT-PE-004','SOL-29'),
('PAT-AL-001','SOL-01'),
('PAT-AL-001','SOL-20'),
('PAT-AL-001','SOL-26'),
('PAT-AL-002','SOL-19'),
('PAT-AL-002','SOL-26'),
('PAT-AL-003','SOL-19'),
('PAT-AL-003','SOL-25'),
('PAT-AL-004','SOL-20'),
('PAT-AL-004','SOL-19'),
('PAT-AL-005','SOL-19'),
('PAT-AL-005','SOL-25'),
('PAT-AL-005','SOL-29'),
('PAT-AL-006','SOL-19'),
('PAT-AL-007','SOL-20'),
('PAT-AL-008','SOL-20'),
('PAT-AL-008','SOL-04'),
('PAT-AL-009','SOL-20'),
('PAT-AL-009','SOL-04'),
('PAT-AL-010','SOL-25'),
('PAT-AL-010','SOL-20'),
('PAT-AL-011','SOL-18'),
('PAT-AL-012','SOL-19'),
('PAT-AL-012','SOL-18'),
('PAT-AL-012','SOL-25'),
('PAT-AL-013','SOL-26'),
('PAT-AL-013','SOL-19'),
('PAT-AL-014','SOL-25'),
('PAT-AL-014','SOL-29'),
('PAT-AL-014','SOL-22'),
('PAT-FU-001','SOL-26'),
('PAT-FU-002','SOL-17'),
('PAT-FU-002','SOL-26'),
('PAT-FU-003','SOL-17'),
('PAT-FU-003','SOL-25'),
('PAT-FU-004','SOL-26'),
('PAT-FU-005','SOL-17'),
('PAT-FU-005','SOL-15'),
('PAT-FU-005','SOL-26'),
('PAT-FU-006','SOL-15'),
('PAT-FU-006','SOL-13'),
('PAT-FU-007','SOL-17'),
('PAT-FU-008','SOL-17'),
('PAT-FU-008','SOL-07'),
('PAT-FU-009','SOL-26'),
('PAT-HU-001','SOL-13'),
('PAT-HU-001','SOL-16'),
('PAT-HU-002','SOL-14'),
('PAT-HU-002','SOL-13'),
('PAT-HU-003','SOL-16'),
('PAT-HU-004','SOL-13'),
('PAT-HU-004','SOL-15'),
('PAT-HU-005','SOL-13'),
('PAT-HU-005','SOL-02'),
('PAT-HU-006','SOL-04'),
('PAT-HU-007','SOL-16'),
('PAT-HU-007','SOL-30'),
('PAT-HU-008','SOL-15'),
('PAT-HU-009','SOL-13'),
('PAT-HU-009','SOL-15'),
('PAT-HU-010','SOL-04'),
('PAT-HU-010','SOL-20'),
('PAT-ME-001','SOL-21'),
('PAT-ME-002','SOL-21'),
('PAT-ME-002','SOL-22'),
('PAT-ME-003','SOL-22'),
('PAT-ME-003','SOL-09'),
('PAT-ME-004','SOL-25'),
('PAT-ME-004','SOL-09'),
('PAT-ME-004','SOL-22'),
('PAT-ME-005','SOL-25'),
('PAT-ME-005','SOL-29'),
('PAT-ME-005','SOL-09'),
('PAT-ME-006','SOL-23'),
('PAT-ME-007','SOL-22'),
('PAT-ME-008','SOL-22'),
('PAT-ME-009','SOL-21'),
('PAT-ME-010','SOL-22'),
('PAT-ME-010','SOL-23'),
('PAT-ME-011','SOL-22'),
('PAT-ME-011','SOL-09'),
('PAT-MA-001','SOL-24'),
('PAT-MA-002','SOL-24'),
('PAT-MA-003','SOL-24'),
('PAT-MA-004','SOL-24'),
('PAT-MA-004','SOL-22'),
('PAT-MA-005','SOL-24'),
('PAT-MA-005','SOL-09'),
('PAT-MA-006','SOL-24'),
('PAT-MA-006','SOL-25'),
('PAT-MA-007','SOL-24'),
('PAT-MA-008','SOL-22'),
('PAT-MA-008','SOL-19'),
('PAT-MA-009','SOL-25'),
('PAT-MA-009','SOL-22'),
('PAT-OU-001','SOL-25'),
('PAT-OU-001','SOL-22'),
('PAT-OU-002','SOL-05'),
('PAT-OU-002','SOL-30'),
('PAT-OU-003','SOL-15'),
('PAT-OU-003','SOL-17'),
('PAT-OU-003','SOL-26'),
('PAT-OU-004','SOL-05'),
('PAT-OU-004','SOL-14'),
('PAT-OU-004','SOL-26'),
('PAT-OU-005','SOL-26'),
('PAT-OU-005','SOL-07'),
('PAT-OU-006','SOL-25'),
('PAT-OU-006','SOL-08'),
('PAT-OU-007','SOL-28'),
('PAT-OU-008','SOL-19'),
('PAT-OU-008','SOL-08'),
('PAT-OU-008','SOL-29'),
('PAT-OU-009','SOL-30'),
('PAT-OU-010','SOL-26')
on conflict do nothing;

insert into kb_services (code,name,unit,not_in_manual) values
('SRV-01','Visita técnica preliminar','Serviço',false),
('SRV-02','Levantamento dimensional','Serviço',false),
('SRV-03','Inspeção visual','m²/serviço',false),
('SRV-04','Levantamento fotográfico','Serviço',false),
('SRV-05','Mapeamento de fissuras','m/m²',false),
('SRV-06','Levantamento de desagregação','m²',false),
('SRV-07','Ensaio de esclerómetro','Ponto',false),
('SRV-08','Ensaio ultrassónico','Ponto',false),
('SRV-09','Deteção de armaduras','Ponto',false),
('SRV-10','Medição de humidade','Ponto',false),
('SRV-11','Termografia','Serviço',false),
('SRV-12','Monitorização de fissuras','Ponto/mês',false),
('SRV-13','Ensaios laboratoriais','Ensaio',false),
('SRV-14','Análise técnica','Serviço',false),
('SRV-15','Relatório técnico','Serviço',false),
('SRV-16','Deslocação','Serviço/km',false),
('SRV-17','Equipamentos especiais','Dia',false),
('SRV-18','Trabalho em altura','Dia',false),
('SRV-19','Acompanhamento de reparação','Dia',false),
('SRV-20','Prova de carga','Serviço',true),
('SRV-21','Prospeção geotécnica','Serviço',true),
('SRV-22','Projeto de reparação/reforço','Serviço',true),
('SRV-23','Nota técnica','Serviço',true),
('SRV-24','Caderno de encargos','Serviço',true),
('SRV-25','Parecer / avaliação sísmica','Serviço',true),
('SRV-26','Nuvem de pontos / laser scanner','Serviço',true),
('SRV-27','Desenhos CAD','Serviço',true),
('SRV-28','Verba fixa de mobilização','Serviço',true),
('SRV-29','Fiscalização de obra','Dia',true)
on conflict (code) do update set name=excluded.name,unit=excluded.unit,not_in_manual=excluded.not_in_manual;

insert into kb_report_sections (code,name,content,not_in_manual) values
('REL-01','Capa','Cliente, local, data, empresa',false),
('REL-02','Objetivo','Motivo da inspeção',false),
('REL-03','Caracterização da estrutura','Tipo, dimensões, idade, materiais, utilização',false),
('REL-04','Metodologia','Inspeção, medições, ensaios, equipamentos',false),
('REL-05','Patologias encontradas','Fichas P-001…: localização, fotografia, dimensão, descrição, causa, severidade',false),
('REL-06','Resultados dos ensaios','Tabelas e gráficos',false),
('REL-07','Diagnóstico','Interpretação técnica',false),
('REL-08','Recomendações','Reparação, reforço, impermeabilização, monitorização, investigação adicional',false),
('REL-09','Conclusão','Estado geral da estrutura',false),
('REL-10','Anexo fotográfico','Fotografias numeradas',true),
('REL-11','Desenhos CAD e mapeamento em planta','Localização das patologias e dos ensaios',true)
on conflict (code) do update set name=excluded.name,content=excluded.content,not_in_manual=excluded.not_in_manual;

insert into kb_equipment (code,name,items,not_in_manual) values
('EQP-D','Diagnóstico','Esclerómetro, ultrassom, pacómetro, detetor de armaduras, medidor de humidade, câmara termográfica, fissurómetros, equipamento de corrosão, georradar',true),
('EQP-M','Medição','Trena, laser, paquímetro, régua de fissuras, nível, nível laser, estação total, GPS',false),
('EQP-C','Documentação','Câmara, drone, tablet, computador, impressora, CAD, software de imagem e de relatórios',false),
('EQP-A','Acesso','Escadas, andaimes, plataformas elevatórias, acesso por cordas (só profissionais habilitados)',false)
on conflict (code) do update set name=excluded.name,items=excluded.items,not_in_manual=excluded.not_in_manual;

insert into kb_materials (code,name,items) values
('MAT-B','Reparação de betão','Argamassa de reparação, microbetão, grout, resina epóxi, selantes, primários, produtos de cura'),
('MAT-A','Armaduras','Passivadores, anticorrosivos, barras de aço, conectores, ancoragens'),
('MAT-I','Impermeabilização','Membranas, argamassas impermeabilizantes, selantes, primários, revestimentos protetores'),
('MAT-R','Reforço','Fibra de carbono ou de vidro, chapas e perfis de aço, barras adicionais, ancoragens, resinas estruturais')
on conflict (code) do update set name=excluded.name,items=excluded.items;

insert into kb_reference_notes (code,title,content,not_in_manual) values
('PKG-1','Pacote 1 — Inspeção básica','Visita, inspeção visual, registo fotográfico, levantamento de patologias, mapeamento, relatório básico',false),
('PKG-2','Pacote 2 — Diagnóstico técnico','Pacote 1 + esclerómetro, pacómetro, medição de fissuras e humidade, análise técnica, relatório detalhado',false),
('PKG-3','Pacote 3 — Diagnóstico completo','Inspeção detalhada, levantamento dimensional, ensaios não destrutivos e laboratoriais, monitorização, avaliação estrutural, diagnóstico das causas, recomendações de reparação e reforço, relatório completo',false),
('HSE-1','EPI','Capacete, botas, colete, óculos, luvas, proteção auricular, máscara/respirador, arnês para altura',false),
('HSE-2','Antes de iniciar','Avaliação de risco, isolar a área, verificar acessos, risco de queda de materiais, equipamentos, procedimento de emergência',false),
('HSE-3','Condicionantes de execução','Faseamento, coordenação com a direção do edifício, horário restrito (escolas, hospitais)',true),
('NRM-1','Projeto e avaliação','NP EN 1990 a 1998 (incl. EN 1998-3 avaliação sísmica), ISO 13822 — confirmar edição em vigor',true),
('NRM-2','Betão','NP EN 206, NP EN 1504, NP EN 12390; classes de exposição XC, XD, XS, XF, XA',true),
('NRM-3','Ensaios','NP EN 12504-1/-2/-4, NP EN 13791, EN 14630, EN 14629, EN 1542, ASTM C876',true),
('NRM-4','Regulamentos históricos','RSA/REBAP (1983), RGEU, RJUE',true),
('SEC-1','Estado de conservação','Escala 1 (péssimo) a 5 (excelente) do método de avaliação de imóveis — confirmar legislação em vigor',true),
('FIC-1','Ficha de patologia','Código P-001, patologia PAT, elemento ELE, localização, dimensão, profundidade, armadura exposta, corrosão, fotografia IMG, causa CAU, severidade SEV, ensaio ENS, recomendação SOL, origem do dado',false)
on conflict (code) do update set title=excluded.title,content=excluded.content,not_in_manual=excluded.not_in_manual;

-- Vista de leitura: patologia com causas, ensaios e soluções
create or replace view kb_pathologies_full as
select p.code, g.name as group_name, p.name, p.sev_min, p.sev_max, p.not_in_manual,
  (select array_agg(cause_code order by cause_code) from kb_pathology_causes where pathology_code = p.code) as causes,
  (select array_agg(test_code order by test_code) from kb_pathology_tests where pathology_code = p.code) as tests,
  (select array_agg(solution_code order by solution_code) from kb_pathology_solutions where pathology_code = p.code) as solutions
from kb_pathologies p join kb_pathology_groups g on g.code = p.group_code where p.active;

-- Segurança: leitura para utilizadores autenticados; escrita para ADMIN, MANAGER e ENGINEER (my_role() vem do 001)
do $$ declare t text; begin
  foreach t in array array['kb_construction_types','kb_elements','kb_causes','kb_tests','kb_solutions','kb_severity','kb_pathology_groups','kb_pathologies','kb_pathology_causes','kb_pathology_tests','kb_pathology_solutions','kb_services','kb_client_info_items','kb_report_sections','kb_equipment','kb_materials','kb_reference_notes'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "kb_ler" on %I', t);
    execute format('create policy "kb_ler" on %I for select using (auth.uid() is not null)', t);
    execute format('drop policy if exists "kb_escrever" on %I', t);
    execute format('create policy "kb_escrever" on %I for all using (my_role() in (''ADMIN'',''MANAGER'',''ENGINEER'')) with check (my_role() in (''ADMIN'',''MANAGER'',''ENGINEER''))', t);
  end loop; end $$;
