-- Base técnica de instalações hidráulicas (águas e esgotos), termos de pesquisa geridos na base de dados
-- e serviços de diagnóstico hidráulico. Preços dos serviços novos: 0 (a definir pelo engenheiro).
-- Os registos novos ficam com not_in_manual = true: precisam de validação de um engenheiro.

insert into kb_pathology_groups(code,name) values ('IH','Instalações hidráulicas (águas e esgotos)') on conflict (code) do update set name=excluded.name;
insert into kb_causes(code,name,not_in_manual) values
('CAU-29','Corrosão, incrustação ou envelhecimento da tubagem',true),
('CAU-30','Junta, ligação ou acessório deficiente',true),
('CAU-31','Pressão de serviço inadequada',true),
('CAU-32','Obstrução ou declive insuficiente na rede de drenagem',true),
('CAU-33','Tubagem embutida sem proteção ou acesso para manutenção',true)
on conflict (code) do nothing;
insert into kb_tests(code,name,test_group,not_in_manual) values
('ENS-90','Prova de pressão / estanquidade da rede de abastecimento','Hidráulica',true),
('ENS-91','Deteção acústica e correlação de fugas','Hidráulica',true),
('ENS-92','Inspeção por vídeo (CCTV) de coletores e ramais','Hidráulica',true),
('ENS-93','Ensaio de estanquidade da rede de esgoto','Hidráulica',true),
('ENS-94','Medição de pressão e caudal nos pontos de consumo','Hidráulica',true),
('ENS-95','Verificação do contador e ligações (teste de consumo)','Hidráulica',true)
on conflict (code) do nothing;
insert into kb_solutions(code,name,not_in_manual) values
('SOL-31','Reparação ou substituição de troço de tubagem',true),
('SOL-32','Substituição da rede embutida',true),
('SOL-33','Desobstrução e correção de declives ou ventilação da rede de esgoto',true),
('SOL-34','Reparação ou substituição de válvulas, acessórios e contador',true),
('SOL-35','Regularização da pressão (redutor, grupo hidropressor)',true),
('SOL-36','Reposição de reboco e revestimento após corrigir a origem da humidade',true)
on conflict (code) do nothing;
insert into kb_pathologies(code,group_code,name,sev_min,sev_max,not_in_manual) values
('PAT-IH-001','IH','Fuga em tubagem ou ligação de abastecimento de água',2,3,true),
('PAT-IH-002','IH','Fuga ou rotura na rede de drenagem de esgoto',2,3,true),
('PAT-IH-003','IH','Pressão ou caudal insuficiente nos pontos de consumo',1,2,true),
('PAT-IH-004','IH','Tubagens embutidas degradadas ou danificadas',2,3,true),
('PAT-IH-005','IH','Caixa de contador, válvulas e acessórios com desgaste ou fuga',1,2,true),
('PAT-IH-006','IH','Obstrução ou funcionamento deficiente da rede de drenagem',2,2,true),
('PAT-HU-011','HU','Destacamento de reboco e revestimento por humidade',1,2,true)
on conflict (code) do nothing;
insert into kb_pathology_causes(pathology_code,cause_code) values
('PAT-IH-001','CAU-29'),
('PAT-IH-001','CAU-30'),
('PAT-IH-001','CAU-31'),
('PAT-IH-001','CAU-17'),
('PAT-IH-002','CAU-30'),
('PAT-IH-002','CAU-32'),
('PAT-IH-002','CAU-29'),
('PAT-IH-002','CAU-10'),
('PAT-IH-003','CAU-31'),
('PAT-IH-003','CAU-29'),
('PAT-IH-004','CAU-29'),
('PAT-IH-004','CAU-33'),
('PAT-IH-004','CAU-25'),
('PAT-IH-004','CAU-18'),
('PAT-IH-005','CAU-29'),
('PAT-IH-005','CAU-17'),
('PAT-IH-005','CAU-30'),
('PAT-IH-006','CAU-32'),
('PAT-IH-006','CAU-17'),
('PAT-HU-011','CAU-03'),
('PAT-HU-011','CAU-24'),
('PAT-HU-011','CAU-17'),
('PAT-HU-003','CAU-29'),
('PAT-HU-003','CAU-30'),
('PAT-HU-008','CAU-32')
on conflict do nothing;
insert into kb_pathology_tests(pathology_code,test_code) values
('PAT-IH-001','ENS-01'),
('PAT-IH-001','ENS-90'),
('PAT-IH-001','ENS-91'),
('PAT-IH-001','ENS-95'),
('PAT-IH-001','ENS-30'),
('PAT-IH-001','ENS-31'),
('PAT-IH-002','ENS-01'),
('PAT-IH-002','ENS-92'),
('PAT-IH-002','ENS-93'),
('PAT-IH-002','ENS-42'),
('PAT-IH-003','ENS-94'),
('PAT-IH-003','ENS-90'),
('PAT-IH-003','ENS-95'),
('PAT-IH-004','ENS-01'),
('PAT-IH-004','ENS-43'),
('PAT-IH-004','ENS-42'),
('PAT-IH-004','ENS-90'),
('PAT-IH-004','ENS-91'),
('PAT-IH-005','ENS-01'),
('PAT-IH-005','ENS-95'),
('PAT-IH-005','ENS-90'),
('PAT-IH-006','ENS-01'),
('PAT-IH-006','ENS-92'),
('PAT-IH-006','ENS-93'),
('PAT-HU-011','ENS-01'),
('PAT-HU-011','ENS-30'),
('PAT-HU-011','ENS-31'),
('PAT-HU-003','ENS-90'),
('PAT-HU-003','ENS-91'),
('PAT-HU-008','ENS-92'),
('PAT-HU-008','ENS-93')
on conflict do nothing;
insert into kb_pathology_solutions(pathology_code,solution_code) values
('PAT-IH-001','SOL-31'),
('PAT-IH-001','SOL-34'),
('PAT-IH-001','SOL-16'),
('PAT-IH-002','SOL-31'),
('PAT-IH-002','SOL-33'),
('PAT-IH-002','SOL-16'),
('PAT-IH-003','SOL-35'),
('PAT-IH-003','SOL-31'),
('PAT-IH-003','SOL-34'),
('PAT-IH-004','SOL-32'),
('PAT-IH-004','SOL-31'),
('PAT-IH-004','SOL-36'),
('PAT-IH-005','SOL-34'),
('PAT-IH-005','SOL-30'),
('PAT-IH-006','SOL-33'),
('PAT-IH-006','SOL-30'),
('PAT-HU-011','SOL-16'),
('PAT-HU-011','SOL-36'),
('PAT-HU-003','SOL-31'),
('PAT-HU-008','SOL-33')
on conflict do nothing;
insert into public.services(service_id,category,name,unit,selling_price,technical_basis) values
('PRESS_EST','NDT','Prova de pressão / estanquidade da rede de abastecimento','ensaio',0,'Deteção de perdas de pressão e fugas. Preço a definir pelo engenheiro.'),
('DET_FUGAS','NDT','Deteção acústica e correlação de fugas','zona',0,'Localização de fugas em rede enterrada ou embutida. Preço a definir pelo engenheiro.'),
('CCTV_ESG','NDT','Inspeção por vídeo (CCTV) de coletores e ramais','troço',0,'Estado interior, obstruções e roturas da rede de esgoto. Preço a definir pelo engenheiro.'),
('EST_ESG','NDT','Ensaio de estanquidade da rede de esgoto','troço',0,'Verificação de fugas na rede de drenagem. Preço a definir pelo engenheiro.'),
('MED_PRESS','NDT','Medição de pressão e caudal nos pontos de consumo','ponto',0,'Diagnóstico de baixa pressão ou caudal. Preço a definir pelo engenheiro.'),
('CONT_VERIF','NDT','Verificação do contador e ligações (teste de consumo)','un',0,'Consumo com pontos fechados indica fuga. Preço a definir pelo engenheiro.')
on conflict (service_id) do nothing;
insert into public.kb_test_services(test_code,service_id) values
('ENS-90','PRESS_EST'),
('ENS-91','DET_FUGAS'),
('ENS-92','CCTV_ESG'),
('ENS-93','EST_ESG'),
('ENS-94','MED_PRESS'),
('ENS-95','CONT_VERIF')
on conflict do nothing;
insert into public.kb_solution_services(solution_code,service_id) values
('SOL-31','PROJ_REAB'),
('SOL-32','PROJ_REAB'),
('SOL-33','PROJ_REAB'),
('SOL-34','PROJ_REAB'),
('SOL-35','PROJ_REAB'),
('SOL-36','PROJ_REAB')
on conflict do nothing;

create table if not exists public.kb_pathology_terms (
  pathology_code text not null references public.kb_pathologies(code) on delete cascade,
  term text not null,
  primary key (pathology_code, term));
comment on table public.kb_pathology_terms is 'Expressões (sem acentos) que identificam uma patologia num pedido. Editável por ADMIN/MANAGER/ENGINEER.';
insert into public.kb_pathology_terms(pathology_code,term) values
('PAT-AL-001','fissura vertical em parede'),
('PAT-AL-001','fissuras verticais na alvenaria'),
('PAT-AL-002','fissura diagonal em parede'),
('PAT-AL-002','fissura em cunhal'),
('PAT-AL-002','fissuras nos cantos'),
('PAT-AL-004','fissura junto a janela'),
('PAT-AL-004','fissura em torno de vao'),
('PAT-AL-004','fissuras junto a porta'),
('PAT-BA-001','fissura vertical'),
('PAT-BA-001','fissuras verticais'),
('PAT-BA-001','fenda vertical'),
('PAT-BA-002','fissura horizontal'),
('PAT-BA-002','fissuras horizontais'),
('PAT-BA-003','fissura diagonal'),
('PAT-BA-003','fissuras diagonais'),
('PAT-BA-003','fissura inclinada'),
('PAT-BA-004','fissura em mapa'),
('PAT-BA-004','fissuras em mapa'),
('PAT-BA-004','fissuracao em mapa'),
('PAT-BA-005','fissura passante'),
('PAT-BA-005','rachadura profunda'),
('PAT-BA-005','fissura profunda'),
('PAT-BA-021','destacamento do betao'),
('PAT-BA-021','betao destacado'),
('PAT-BA-021','queda de betao'),
('PAT-BA-030','armadura exposta'),
('PAT-BA-030','armaduras expostas'),
('PAT-BA-030','ferro a vista'),
('PAT-BA-030','aco exposto'),
('PAT-BA-031','corrosao por carbonatacao'),
('PAT-BA-031','corrosao da armadura'),
('PAT-BA-032','corrosao por cloretos'),
('PAT-BA-032','corrosao por cloreto'),
('PAT-BA-035','manchas de ferrugem'),
('PAT-BA-035','ferrugem no betao'),
('PAT-BA-035','expansao do betao'),
('PAT-BA-044','carbonatacao atingindo a armadura'),
('PAT-BA-044','profundidade de carbonatacao'),
('PAT-BA-045','contaminacao por cloretos'),
('PAT-BA-045','teor de cloretos'),
('PAT-BA-045','cloretos no betao'),
('PAT-BA-054','baixa resistencia do betao'),
('PAT-BA-054','resistencia inferior a de projeto'),
('PAT-BA-054','betao fraco'),
('PAT-BA-056','recobrimento insuficiente'),
('PAT-BA-056','pouco recobrimento'),
('PAT-BA-056','cobrimento insuficiente'),
('PAT-BA-060','betao exposto a agua'),
('PAT-BA-060','submersao prolongada'),
('PAT-BA-060','contacto permanente com agua'),
('PAT-BA-061','sobrecarga estrutural'),
('PAT-BA-061','carga excessiva'),
('PAT-FU-006','nivel freatico'),
('PAT-FU-006','agua subterranea'),
('PAT-FU-006','cave inundada'),
('PAT-FU-006','caves inundadas'),
('PAT-FU-006','inundacao de cave'),
('PAT-HU-001','infiltracao na cobertura'),
('PAT-HU-001','infiltracao em cobertura'),
('PAT-HU-001','infiltracao no terraco'),
('PAT-HU-001','telhado com infiltracao'),
('PAT-HU-002','infiltracao na fachada'),
('PAT-HU-002','infiltracao em fachada'),
('PAT-HU-002','junta aberta na fachada'),
('PAT-HU-002','humidade na fachada'),
('PAT-HU-003','fuga de agua'),
('PAT-HU-003','fugas de agua'),
('PAT-HU-003','rotura de tubagem'),
('PAT-HU-003','tubagem com fuga'),
('PAT-HU-003','fuga em tubagem'),
('PAT-HU-003','infiltracao de casa de banho'),
('PAT-HU-003','infiltracao proveniente de tubagem'),
('PAT-HU-003','mancha de humidade no teto'),
('PAT-HU-004','infiltracao em cave'),
('PAT-HU-004','humidade em cave'),
('PAT-HU-004','parede enterrada'),
('PAT-HU-004','parede de cave com humidade'),
('PAT-HU-005','reservatorio com perda'),
('PAT-HU-005','perda de estanquidade'),
('PAT-HU-005','fuga em reservatorio'),
('PAT-HU-006','condensacao'),
('PAT-HU-006','ponte termica'),
('PAT-HU-006','pontes termicas'),
('PAT-HU-007','bolor'),
('PAT-HU-007','bolores'),
('PAT-HU-007','mofo'),
('PAT-HU-007','fungos na parede'),
('PAT-HU-008','drenagem deficiente'),
('PAT-HU-008','acumulacao de agua'),
('PAT-HU-008','agua acumulada'),
('PAT-HU-008','ma drenagem'),
('PAT-HU-008','ralo com agua'),
('PAT-HU-009','humidade ascensional'),
('PAT-HU-009','humidade por capilaridade'),
('PAT-HU-009','subida capilar'),
('PAT-HU-010','eflorescencia'),
('PAT-HU-010','eflorescencias'),
('PAT-HU-010','cristalizacao de sais'),
('PAT-HU-010','sais soluveis'),
('PAT-HU-011','destacamento de reboco'),
('PAT-HU-011','reboco destacado'),
('PAT-HU-011','reboco empolado'),
('PAT-HU-011','pintura empolada'),
('PAT-HU-011','descasque de pintura'),
('PAT-HU-011','reboco a cair'),
('PAT-IH-001','fuga em tubagem de abastecimento'),
('PAT-IH-001','fuga de agua em tubagem'),
('PAT-IH-001','tubagem de abastecimento com fuga'),
('PAT-IH-001','fuga de agua'),
('PAT-IH-001','rotura de tubagem'),
('PAT-IH-001','uniao com fuga'),
('PAT-IH-001','agua a jorrar'),
('PAT-IH-002','fuga na rede de esgoto'),
('PAT-IH-002','fuga de esgoto'),
('PAT-IH-002','rotura de coletor'),
('PAT-IH-002','fuga na rede de drenagem'),
('PAT-IH-002','fuga em tubagem de esgoto'),
('PAT-IH-003','baixa pressao'),
('PAT-IH-003','pressao insuficiente'),
('PAT-IH-003','fraco caudal'),
('PAT-IH-003','baixo caudal'),
('PAT-IH-003','pouca pressao de agua'),
('PAT-IH-004','tubagem embutida'),
('PAT-IH-004','tubagens embutidas'),
('PAT-IH-004','tubagens embutidas danificadas'),
('PAT-IH-004','tubagem corroida'),
('PAT-IH-004','corrosao de tubagem'),
('PAT-IH-004','tubagens danificadas'),
('PAT-IH-005','caixa do contador'),
('PAT-IH-005','contador de agua'),
('PAT-IH-005','caixa de agua'),
('PAT-IH-005','caixa de valvulas'),
('PAT-IH-005','desgaste do contador'),
('PAT-IH-006','entupimento'),
('PAT-IH-006','obstrucao da rede'),
('PAT-IH-006','ralo entupido'),
('PAT-IH-006','refluxo de esgoto'),
('PAT-IH-006','drenagem lenta')
on conflict do nothing;
alter table public.kb_pathology_terms enable row level security;
drop policy if exists "kb_ler" on public.kb_pathology_terms;
create policy "kb_ler" on public.kb_pathology_terms for select using (auth.uid() is not null);
drop policy if exists "kb_escrever" on public.kb_pathology_terms;
create policy "kb_escrever" on public.kb_pathology_terms for all using (my_role() in ('ADMIN','MANAGER','ENGINEER')) with check (my_role() in ('ADMIN','MANAGER','ENGINEER'));
grant select, insert, update, delete on public.kb_pathology_terms to authenticated;
